import '../../../../core/models/entity_meta.dart';
import '../../../../core/services/entity_service.dart';

const rbacModuleEntityMeta = EntityMeta(
  entityName: "Route Shop Link",
  entityNameLower: "route shop link",
  entityNamePlural: "Route Shop Links",
  entityNamePluralLower: "route shop links",
);

class ModelRouteShopLinkFields {
  static const String table = 'route_shop_links';
  static const String tableViewWithForeignKeyLabels = 'view_route_shop_links';

  static const String linkId = 'link_id';
  static const String routeId = 'route_id';
  static const String shopId = 'shop_id';
  static const String visitOrder = 'visit_order';
  static const String createdAt = 'created_at';
  static const String updatedAt = 'updated_at';

  static const Map<String, String> labels = {
    linkId: 'Route-Shop Link',
    routeId: 'Route',
    shopId: 'Shop',
    visitOrder: 'Visit Order',
    createdAt: 'Created At',
    updatedAt: 'Updated At',
  };

  static String getLabel(String field) => labels[field] ?? field;
}

class ModelRouteShopLink {
  final String? linkId; // nullable, generated by DB
  final String? routeId; // nullable FK
  final String? shopId; // nullable FK
  final int? visitOrder; // nullable
  final DateTime? createdAt; // nullable, DB default
  final DateTime? updatedAt; // nullable, DB default
  final Map<String, dynamic> _resolvedLabels;

  ModelRouteShopLink({
    this.linkId,
    this.routeId,
    this.shopId,
    this.visitOrder,
    this.createdAt,
    this.updatedAt,
    Map<String, dynamic>? resolvedLabels,
  }) : _resolvedLabels = resolvedLabels ?? const {};

  Map<String, dynamic> get resolvedLabels => _resolvedLabels;

  factory ModelRouteShopLink.fromMap(Map<String, dynamic> map) {
    final labelEntries = <String, dynamic>{};
    for (final entry in map.entries) {
      if (entry.key.endsWith('_label')) {
        labelEntries[entry.key] = entry.value;
      }
    }

    return ModelRouteShopLink(
      linkId: map[ModelRouteShopLinkFields.linkId],
      routeId: map[ModelRouteShopLinkFields.routeId],
      shopId: map[ModelRouteShopLinkFields.shopId],
      visitOrder: map[ModelRouteShopLinkFields.visitOrder],
      createdAt: _parseDate(map[ModelRouteShopLinkFields.createdAt]),
      updatedAt: _parseDate(map[ModelRouteShopLinkFields.updatedAt]),
      resolvedLabels: labelEntries,
    );
  }

  Map<String, dynamic> toMap() {
    return {
      if (linkId != null) ModelRouteShopLinkFields.linkId: linkId,
      if (routeId != null) ModelRouteShopLinkFields.routeId: routeId,
      if (shopId != null) ModelRouteShopLinkFields.shopId: shopId,
      if (visitOrder != null) ModelRouteShopLinkFields.visitOrder: visitOrder,
      if (createdAt != null)
        ModelRouteShopLinkFields.createdAt: createdAt!.toIso8601String(),
      if (updatedAt != null)
        ModelRouteShopLinkFields.updatedAt: updatedAt!.toIso8601String(),
    };
  }

  Map<String, dynamic> toJson() {
    return {
      'linkId': linkId,
      'routeId': routeId,
      'shopId': shopId,
      'createdAt': createdAt?.toIso8601String(),
      'updatedAt': updatedAt?.toIso8601String(),
      'visitOrder': visitOrder,
    };
  }

  factory ModelRouteShopLink.fromJson(Map<String, dynamic> json) {
    return ModelRouteShopLink(
      linkId: json['linkId'] as String,
      routeId: json['routeId'] as String?,
      shopId: json['shopId'] as String?,
      createdAt: DateTime.tryParse(json['createdAt'] ?? '') ?? DateTime.now(),
      updatedAt: DateTime.tryParse(json['updatedAt'] ?? '') ?? DateTime.now(),
      visitOrder: json['visitOrder'] as int?,
    );
  }

  static DateTime? _parseDate(dynamic value) {
    if (value == null) return null;
    if (value is DateTime) return value;
    return DateTime.tryParse(value.toString());
  }

  ModelRouteShopLink copyWith({
    String? linkId,
    String? routeId,
    String? shopId,
    int? visitOrder,
    DateTime? createdAt,
    DateTime? updatedAt,
    Map<String, dynamic>? resolvedLabels,
  }) {
    return ModelRouteShopLink(
      linkId: linkId ?? this.linkId,
      routeId: routeId ?? this.routeId,
      shopId: shopId ?? this.shopId,
      visitOrder: visitOrder ?? this.visitOrder,
      createdAt: createdAt ?? this.createdAt,
      updatedAt: updatedAt ?? this.updatedAt,
      resolvedLabels: resolvedLabels ?? _resolvedLabels,
    );
  }
}

class ModelRouteShopLinkMapper implements EntityMapper<ModelRouteShopLink> {
  @override
  ModelRouteShopLink fromMap(Map<String, dynamic> map) =>
      ModelRouteShopLink.fromMap(map);

  @override
  Map<String, dynamic> toMap(ModelRouteShopLink entity) => entity.toMap();
}
