import '../../../../core/models/entity_meta.dart';
import '../../../../core/services/entity_service.dart';

const routeEntityMeta = EntityMeta(
  entityName: 'Route',
  entityNamePlural: 'Routes',
  entityNameLower: 'route',
  entityNamePluralLower: 'routes',
);

class ModelRouteFields {
  static const String table = 'routes';

  static const String routeId = 'route_id';
  static const String routeName = 'route_name';
  static const String routeNote = 'route_note';
  static const String isActive = 'is_active';
  static const String createdAt = 'created_at';
  static const String updatedAt = 'updated_at';
}

class ModelRoute {
  final String? routeId; // nullable, generated by DB
  final String routeName; // required
  final String? routeNote; // nullable
  final bool isActive; // default true
  final DateTime? createdAt; // nullable, DB default
  final DateTime? updatedAt; // nullable, DB default

  ModelRoute({
    this.routeId,
    required this.routeName,
    this.routeNote,
    this.isActive = true,
    this.createdAt,
    this.updatedAt,
  });

  factory ModelRoute.fromMap(Map<String, dynamic> map) {
    return ModelRoute(
      routeId: map[ModelRouteFields.routeId],
      routeName: map[ModelRouteFields.routeName],
      routeNote: map[ModelRouteFields.routeNote],
      isActive: map[ModelRouteFields.isActive] ?? true,
      createdAt: map[ModelRouteFields.createdAt] != null
          ? DateTime.tryParse(map[ModelRouteFields.createdAt])
          : null,
      updatedAt: map[ModelRouteFields.updatedAt] != null
          ? DateTime.tryParse(map[ModelRouteFields.updatedAt])
          : null,
    );
  }

  Map<String, dynamic> toMap() {
    return {
      if (routeId != null) ModelRouteFields.routeId: routeId,
      ModelRouteFields.routeName: routeName,
      if (routeNote != null) ModelRouteFields.routeNote: routeNote,
      ModelRouteFields.isActive: isActive,
      if (createdAt != null)
        ModelRouteFields.createdAt: createdAt!.toIso8601String(),
      if (updatedAt != null)
        ModelRouteFields.updatedAt: updatedAt!.toIso8601String(),
    };
  }

  Map<String, dynamic> toJson() {
    return {
      'routeId': routeId,
      'routeName': routeName,
      'routeNote': routeNote,
      'isActive': isActive,
      'createdAt': createdAt?.toIso8601String(),
      'updatedAt': updatedAt?.toIso8601String(),
    };
  }

  factory ModelRoute.fromJson(Map<String, dynamic> json) {
    return ModelRoute(
      routeId: json['routeId'] as String,
      routeName: json['routeName'] as String,
      routeNote: json['routeNote'] as String?,
      isActive: json['isActive'] as bool? ?? true,
      createdAt: DateTime.tryParse(json['createdAt'] ?? '') ?? DateTime.now(),
      updatedAt: DateTime.tryParse(json['updatedAt'] ?? '') ?? DateTime.now(),
    );
  }
}

class ModelRouteMapper implements EntityMapper<ModelRoute> {
  @override
  ModelRoute fromMap(Map<String, dynamic> map) => ModelRoute.fromMap(map);

  @override
  Map<String, dynamic> toMap(ModelRoute entity) => entity.toMap();
}
